# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d01e6815f7f74e5047e1396a4c5ee8f90b75165aa89c349e1daaf2e5199e02f9d842272b6b4d92a2e431cfe7043be345e2610788fd27df1c34c44b03dadbb26
  
  facebook_app_id: 1671019106532157
  facebook_app_secret: e0ec026d65afb426cb059aa3b0a571d7

  twitter_app_id: n4hV4GVCkrP04R1yKFTA45Li5
  twitter_app_secret: jUPacICRdCbuLHckSCK3sToWUNJUBwohWr9kkxBIjTKBSXQjXe  


test:
  secret_key_base: 0a0e460ed32d2a23c0782f524916311a2ddd48cb05511cfb931200b11d186201e4877ba470252e073d217de54794134fb462541f27f6211266aad46472c53f2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
